version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: black
        versions:
          - 21.4b0
          - 21.4b1
      - dependency-name: pydantic
        versions:
          - "1.8"
      - dependency-name: httpx
        versions:
          - 0.17.0
